### ISSUE TITLE
Comparative adjectives ("-er") tagged as NN instead of JJR

### ISSUE THREAD

**Issue by noahlange** [winkjs/wink-lexicon#13]
I'd recommend testing unknown words against the "-er" suffix [here](https://github.com/winkjs/wink-lexicon/blob/master/src/unknown-words.js#L48) in addition to "-ier". Many JJRs are being incorrectly tagged as NNs - "quicker," "taller," "smarter," etc.

It looks like the only unknown words that will return as JJRs are words suffixed with "-ier," which might be a typo, though it's also correct -- adjectives ending in "-y" are indeed suffixed with "-ier" ("happier," "angrier," etc.).

More discussions on [Wikipedia](https://en.wikipedia.org/wiki/Comparison_(grammar)#Morphological_comparison) and [here](https://sites.google.com/site/partofspeechhelp/#TOC-JJR).

**Comment by sanjayaksaxena** [comment]
Hi @noahlange 

Your observation is correct. 

But with `er`-rule included words like diameter, _alzheimer_, _poker_, _diver_, _roger_, _enquirer_, _cylinder_, _bumper_ will also get tagged as `JJR`! Also the word _smarter_ is mostly `RBR` and rarely `JJR`. The challenge is how to tag out-of-vocabulary (OOV) words.

Please consider using [`updateLexicon()`](http://winkjs.org/wink-pos-tagger/Tagger.html#updateLexicon) api of [`wink-pos-tagger`](http://winkjs.org/wink-pos-tagger/index.html) to define the OOV words that you need frequently, while we are working on the next generation tools.

Best
Sanjaya
